services:
  - type: web
    name: flask-magic-wish
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:10000"
    autoDeploy: true
