[DEFAULT]
network = "mainnet"

[[CURRENCIES]]
code = "JIN"
issuer = "rfr3bTEfyY14Ce7zMf9itmdttmxxHKHuCY"
display_decimals = 2
name = "Magic Token JIN"
desc = "Magic Token JIN - The ultimate magical token on the XRP Ledger"
icon = "https://magicdev.net/static/images/Magic.png"

[[ACCOUNTS]]
address = "rfr3bTEfyY14Ce7zMf9itmdttmxxHKHuCY"
url = "https://magicdev.net"
